In [0]:
import numpy as np

Every Node object represent a node on the search tree.

It stores
1.   The state: position of all the tiles
2.   A reference to the parent node
3.   g: cost of reaching the node (considering cost of each edge in the tree as 1)
4.   a: represents the action applied on parent node to reach this node

and has a funcitons:
* expand(): 
    * Moves the position of the blank and returns an array (a list) of Nodes obtained
    * Does not consist parent state done by checking 'Node.a' values 




In [0]:
class Node:
  def __init__(self, state, parent, cost, action):
    self.currentState = state
    self.parent = parent
    self.g = cost
    self.a = action # Action applied to reach the state L, R, T or D

  def expand(self):
    i, j = np.where(self.currentState == 0)
    i, j = int(i), int(j) # Current position of the blank -> {0}
    children = []

    # Move the blank one step at a time
    # Actions: D, R, L and T denote the movement of 0 in 4 directions
    if self.a != 'D' and i - 1 >= 0:
        s = self.currentState.copy()
        s[i][j] = s[i - 1][j]
        s[i - 1][j] = 0
        children.append(Node(s, self, self.g + 1, 'T'))

    if self.a != 'R' and j - 1 >= 0:
        s = self.currentState.copy()
        s[i][j] = s[i][j - 1]
        s[i][j - 1] = 0
        children.append(Node(s, self, self.g + 1, 'L'))
    
    if self.a != 'L' and j + 1 <= 2:
        s = self.currentState.copy()
        s[i][j] = s[i][j + 1]
        s[i][j + 1] = 0
        children.append(Node(s, self, self.g + 1, 'R'))

    if self.a != 'T' and i + 1 <= 2:
        s = self.currentState.copy()
        s[i][j] = s[i + 1][j]
        s[i + 1][j] = 0
        children.append(Node(s, self, self.g + 1, 'D'))
    return children

**IDS**

Calls a funciton recursive DFS infinite times until solution is found

Returns the goal node

In [0]:
def rec_DLS(node, limit, goal):
  # Check if the current node is goal
  if np.allclose(goal, node.currentState): 
    print(f"\nSolution found, cost: {node.g} \n")
    return node
  if limit == 0:
    return 'cutoff'

  c_o = False
  for child in node.expand():
    res = rec_DLS(child, limit - 1, goal)
    if res == 'cutoff':
      c_o = True 
    elif res != 'failure':
      return res
  return 'cutoff' if c_o else 'failure'
    
def IDS(startState, goal):
  l = 0
  while True:
    print(f"Depth: {l}")
    res = rec_DLS(startState, l, goal)
    if res != 'failure':
      if res != 'cutoff':
        return res
      else: 
        print(f"Result: {res}")
        l += 1
    else:
      print("Solution cannot be found")
      return 


Recursive function to print the path to solution

In [0]:
def print_soln(sol):
  if sol.parent == None:
    print(sol.currentState, '\n')
    return
  print_soln(sol.parent)
  print(sol.currentState, "\n")

All the states are represented with a 3x3 array

0 represents the blank tile

Tile movements are implimented by swapping 0 with adjacent elements

In [6]:
puzzle = np.asarray([[7, 2, 4], [5, 0, 6], [8, 3, 1]]) #An example 

goal = list(np.arange(1, 9))
goal.append(0)
goal = np.asarray(goal).reshape(3, 3)

print_soln(IDS(Node(puzzle, None, 0, ""), goal))

Depth: 0
Result: cutoff
Depth: 1
Result: cutoff
Depth: 2
Result: cutoff
Depth: 3
Result: cutoff
Depth: 4
Result: cutoff
Depth: 5
Result: cutoff
Depth: 6
Result: cutoff
Depth: 7
Result: cutoff
Depth: 8
Result: cutoff
Depth: 9
Result: cutoff
Depth: 10
Result: cutoff
Depth: 11
Result: cutoff
Depth: 12
Result: cutoff
Depth: 13
Result: cutoff
Depth: 14
Result: cutoff
Depth: 15
Result: cutoff
Depth: 16
Result: cutoff
Depth: 17
Result: cutoff
Depth: 18
Result: cutoff
Depth: 19
Result: cutoff
Depth: 20

Solution found, cost: 20 

[[7 2 4]
 [5 0 6]
 [8 3 1]] 

[[7 2 4]
 [5 3 6]
 [8 0 1]] 

[[7 2 4]
 [5 3 6]
 [8 1 0]] 

[[7 2 4]
 [5 3 0]
 [8 1 6]] 

[[7 2 4]
 [5 0 3]
 [8 1 6]] 

[[7 2 4]
 [0 5 3]
 [8 1 6]] 

[[0 2 4]
 [7 5 3]
 [8 1 6]] 

[[2 0 4]
 [7 5 3]
 [8 1 6]] 

[[2 4 0]
 [7 5 3]
 [8 1 6]] 

[[2 4 3]
 [7 5 0]
 [8 1 6]] 

[[2 4 3]
 [7 0 5]
 [8 1 6]] 

[[2 4 3]
 [7 1 5]
 [8 0 6]] 

[[2 4 3]
 [7 1 5]
 [0 8 6]] 

[[2 4 3]
 [0 1 5]
 [7 8 6]] 

[[2 4 3]
 [1 0 5]
 [7 8 6]] 

[[2 0 3]
 [1 4 5]
 [7 